# ----------------------------------------------------------------------------------------------------------------------
# Circle CI build workflow
#     See Circle CI configuration reference - https://circleci.com/docs/2.0/configuration-reference/
#     See Circle CI configuration variables - https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
# ----------------------------------------------------------------------------------------------------------------------
version: 2.1
jobs:
  build:
    working_directory: /virtapp
    environment:
      TAG_PFX: 2.1

    docker:
      - image: docker:19-git

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            TAG=$TAG_PFX.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --no-cache -t virtapp/apache:$TAG /innovi
            docker push virtapp/apache:$TAG


# ----------------------------------------------------------------------------------------------------------------------

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context:
            - virtapp
          filters:
            branches:
              only: master

